services:
  db:
    container_name: postgres_db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mess_db
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
  minio:
    container_name: minio
    image: minio/minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - '9000:9000' # API endpoint
      - '9001:9001' # Web console
    volumes:
      - minio_data:/data

volumes:
  db_data:
  minio_data:
